### PR TITLE
Update to K2

### PR DESCRIPTION
**Pull request by ZacSweers**
- Update to Kotlin 2.0.0
- Update to KSP 2.0.0-1.0.21
- Update to MoshiX 0.27.0
- Build against RCP 1.9.0
- Update to new compose compiler gradle plugin setup
  - Add mapping from our compiler options gradle property to known compiler options in compose

### CODE REVIEW

**Comment by ZacSweers** [comment]
TODO - update version compatibility logic for the new compose compiler plugin

**Comment by ZacSweers** [comment]
I've published `0.18.0-alpha01` with the changes up to this point

**Comment by ZacSweers** [comment]
Published `0.18.0-alpha02` with the latest changes from main and updated strong skipping name

**Comment by ZacSweers** [comment]
Published `0.18.0-alpha03` with the changes up to this point, all built against 2.0 final versions

**Review by jhperezd — APPROVED** [review]

**Pull request merged**
